package CLMS;

import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.border.Border;

/**
 *
 * @author Durga Prasad A G (https://durgaprasadag.github.io/dp/)
 */
public class CollegeLibraryManagementSystem extends javax.swing.JFrame {

    Connection cn;
    Statement st;
    String sql;
    ResultSet rs;
    String userName;
    String password;
    boolean passwordFlag = true;
    boolean userNameFlag = true;
    boolean loginFlag = false;
    protected JButton[] buttons;
    
    /**
     * Creates new form CollegeLibraryManagementSystem
     */
    public CollegeLibraryManagementSystem() {
        initComponents();
        allButtons();
        connectToDatabase("SELECT * FROM LIBRARIAN ORDER BY UNAME");
        setHandCursorForButtons();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        BorderLayout = new javax.swing.JPanel();
        CardLayout = new javax.swing.JPanel();
        LibrarianLogin = new jPanelGradient(16, 147, 245, 124, 0, 255);
        loginButton = new javax.swing.JButton();
        passwordHintLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        passwordHintLabel1 = new javax.swing.JLabel();
        toastLabel = new javax.swing.JLabel();
        Dashboard = new jPanelGradient(48, 170, 228, 0, 255, 141);
        studentButton = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        bookInformationBtn = new javax.swing.JButton();
        returnBooksBtn = new javax.swing.JButton();
        manageLibrarianAcBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("College Library Management System");
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon/online-library.png")));
        setResizable(false);

        jDesktopPane1 = new javax.swing.JDesktopPane() {
            @Override
            protected  void paintComponent(java.awt.Graphics g) {
                super.paintComponent(g);
                g.setColor(new java.awt.Color(0,255,141));
                g.fillRect(0, 0, getWidth(), getHeight());
            }
        };
        jDesktopPane1.setBackground(new java.awt.Color(51, 51, 51));
        jDesktopPane1.setPreferredSize(new java.awt.Dimension(960, 720));

        BorderLayout.setBackground(new java.awt.Color(45, 45, 45));
        BorderLayout.setPreferredSize(new java.awt.Dimension(960, 720));
        BorderLayout.setLayout(new java.awt.BorderLayout());

        CardLayout.setBackground(new java.awt.Color(40, 40, 40));
        CardLayout.setPreferredSize(new java.awt.Dimension(960, 720));
        CardLayout.setLayout(new java.awt.CardLayout());

        LibrarianLogin.setBackground(new java.awt.Color(35, 35, 35));
        LibrarianLogin.setPreferredSize(new java.awt.Dimension(960, 720));

        loginButton.setBackground(new java.awt.Color(58, 72, 201));
        loginButton.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        loginButton.setForeground(new java.awt.Color(255, 255, 255));
        loginButton.setText("LOGIN");
        loginButton.setPreferredSize(new java.awt.Dimension(175, 35));
        loginButton.setMnemonic(java.awt.event.KeyEvent.VK_L);
        loginButton.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginButtonFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                loginButtonFocusLost(evt);
            }
        });
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        loginButton.setBorder(new RoundedBorder(5));

        passwordHintLabel.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        passwordHintLabel.setForeground(new java.awt.Color(255, 255, 255));
        passwordHintLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        passwordHintLabel.setMinimumSize(new java.awt.Dimension(75, 30));

        jLabel4.setFont(new java.awt.Font("Lucida Handwriting", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Librarian login");

        userNameTextField.setBackground(new java.awt.Color(72, 91, 200));
        userNameTextField.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        userNameTextField.setForeground(new java.awt.Color(255, 255, 255));
        userNameTextField.setText("username");
        userNameTextField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        userNameTextField.setPreferredSize(new java.awt.Dimension(175, 35));
        userNameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameTextFieldKeyPressed(evt);
            }
        });
        userNameTextField.setBorder(new RoundedBorder(5));

        passwordField.setBackground(new java.awt.Color(72, 91, 200));
        passwordField.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        passwordField.setForeground(new java.awt.Color(255, 255, 255));
        passwordField.setText("password");
        passwordField.setPreferredSize(new java.awt.Dimension(175, 35));
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        passwordField.setBorder(new RoundedBorder(5));
        passwordField.setEchoChar((char) 0);

        passwordHintLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 18)); // NOI18N
        passwordHintLabel1.setForeground(new java.awt.Color(255, 255, 255));
        passwordHintLabel1.setText("Password Hint :");
        passwordHintLabel1.setVisible(false);

        toastLabel.setBackground(new java.awt.Color(54, 45, 205));
        toastLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        toastLabel.setForeground(new java.awt.Color(255, 255, 255));
        toastLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toastLabel.setOpaque(true);
        toastLabel.setBorder(new RoundedBorder(5));
        toastLabel.setVisible(false);
        toastLabel.setPreferredSize(new java.awt.Dimension(345, 35));

        javax.swing.GroupLayout LibrarianLoginLayout = new javax.swing.GroupLayout(LibrarianLogin);
        LibrarianLogin.setLayout(LibrarianLoginLayout);
        LibrarianLoginLayout.setHorizontalGroup(
            LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LibrarianLoginLayout.createSequentialGroup()
                .addContainerGap(296, Short.MAX_VALUE)
                .addGroup(LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(toastLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(290, 290, 290))
            .addGroup(LibrarianLoginLayout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addGroup(LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LibrarianLoginLayout.createSequentialGroup()
                        .addComponent(passwordHintLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(passwordHintLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(passwordField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(loginButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LibrarianLoginLayout.setVerticalGroup(
            LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LibrarianLoginLayout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel4)
                .addGap(50, 50, 50)
                .addComponent(userNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loginButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(LibrarianLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(passwordHintLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordHintLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(toastLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        CardLayout.add(LibrarianLogin, "card2");

        Dashboard.setBackground(new java.awt.Color(193, 207, 137));
        Dashboard.setPreferredSize(new java.awt.Dimension(960, 720));

        studentButton.setBackground(new java.awt.Color(237, 242, 133));
        studentButton.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        studentButton.setForeground(new java.awt.Color(124, 97, 97));
        studentButton.setText("Student");
        studentButton.setToolTipText("Manage Student");
        studentButton.setPreferredSize(new java.awt.Dimension(200, 100));
        studentButton.setMnemonic(java.awt.event.KeyEvent.VK_S);

        studentButton.setBorder(new RoundedBorder(10));
        studentButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentButtonMouseExited(evt);
            }
        });
        studentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentButtonActionPerformed(evt);
            }
        });

        bookBtn.setBackground(new java.awt.Color(57, 139, 241));
        bookBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(255, 255, 255));
        bookBtn.setText("Book");
        bookBtn.setToolTipText("Manage Book");
        bookBtn.setPreferredSize(new java.awt.Dimension(200, 100));
        bookBtn.setMnemonic(java.awt.event.KeyEvent.VK_B);

        bookBtn.setBorder(new RoundedBorder(10));
        bookBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookBtnMouseExited(evt);
            }
        });
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });

        bookInformationBtn.setBackground(new java.awt.Color(77, 219, 162));
        bookInformationBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        bookInformationBtn.setForeground(new java.awt.Color(102, 102, 0));
        bookInformationBtn.setText("Book Information");
        bookInformationBtn.setToolTipText("Manage Book Information");
        bookInformationBtn.setPreferredSize(new java.awt.Dimension(200, 100));
        bookInformationBtn.setMnemonic(java.awt.event.KeyEvent.VK_M);

        bookInformationBtn.setBorder(new RoundedBorder(10));
        bookInformationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bookInformationBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bookInformationBtnMouseExited(evt);
            }
        });
        bookInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookInformationBtnActionPerformed(evt);
            }
        });

        returnBooksBtn.setBackground(new java.awt.Color(253, 140, 4));
        returnBooksBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        returnBooksBtn.setForeground(new java.awt.Color(255, 255, 255));
        returnBooksBtn.setText("Return Books");
        returnBooksBtn.setToolTipText("Manage Return Books");
        returnBooksBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        returnBooksBtn.setPreferredSize(new java.awt.Dimension(200, 100));
        returnBooksBtn.setMnemonic(java.awt.event.KeyEvent.VK_R);

        returnBooksBtn.setBorder(new RoundedBorder(10));
        returnBooksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnBooksBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnBooksBtnMouseExited(evt);
            }
        });
        returnBooksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBooksBtnActionPerformed(evt);
            }
        });

        manageLibrarianAcBtn.setBackground(new java.awt.Color(236, 88, 88));
        manageLibrarianAcBtn.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        manageLibrarianAcBtn.setForeground(new java.awt.Color(255, 255, 255));
        manageLibrarianAcBtn.setText("<html>\nManage Librarian\n<br>\n<u>A</u>ccount\n</html>");
        manageLibrarianAcBtn.setToolTipText("Manage your account");
        manageLibrarianAcBtn.setPreferredSize(new java.awt.Dimension(200, 100));
        manageLibrarianAcBtn.setMnemonic(java.awt.event.KeyEvent.VK_A);

        manageLibrarianAcBtn.setBorder(new RoundedBorder(10));
        manageLibrarianAcBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manageLibrarianAcBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manageLibrarianAcBtnMouseExited(evt);
            }
        });
        manageLibrarianAcBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageLibrarianAcBtnActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Lucida Handwriting", 1, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Manage Library");

        javax.swing.GroupLayout DashboardLayout = new javax.swing.GroupLayout(Dashboard);
        Dashboard.setLayout(DashboardLayout);
        DashboardLayout.setHorizontalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(studentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(130, 130, 130)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(manageLibrarianAcBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(returnBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)
                .addComponent(bookBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );
        DashboardLayout.setVerticalGroup(
            DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jLabel8)
                .addGap(82, 82, 82)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnBooksBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(studentButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108)
                .addGroup(DashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(manageLibrarianAcBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookInformationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(181, Short.MAX_VALUE))
        );

        CardLayout.add(Dashboard, "card4");

        BorderLayout.add(CardLayout, java.awt.BorderLayout.CENTER);

        jDesktopPane1.setLayer(BorderLayout, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(BorderLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addComponent(BorderLayout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Connects to database on application start up.
     */
    private void connectToDatabase(String s) {
        try {
            Class.forName("oracle.jdbc.OracleDriver");
            cn = DriverManager.getConnection("jdbc:oracle:thin:@localhost:1521/SID", "username", "password");
            st = cn.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            rs = st.executeQuery(s);
            rs.first();
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error : " + ex);
        }
    }

    private void allButtons() {
        buttons = new JButton[]{loginButton, studentButton, returnBooksBtn, 
            bookBtn, bookInformationBtn, manageLibrarianAcBtn};
    }
    
    /**
     * On Button hover, Arrow cursor changes to hand cursor.
     */
    private void setHandCursorForButtons() {
        
        for (JButton jb : buttons) {
            jb.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        }
    }

    public class jPanelGradient extends javax.swing.JPanel {

        int color1RR, color1GG, color1BB;
        int color2RR, color2GG, color2BB;

        public jPanelGradient(int c1, int c2, int c3, int c4, int c5, int c6) {
            color1RR = c1;
            color1GG = c2;
            color1BB = c3;
            color2RR = c4;
            color2GG = c5;
            color2BB = c6;
        }

        @Override
        protected void paintComponent(java.awt.Graphics g) {
            java.awt.Graphics2D g2d = (java.awt.Graphics2D) g;
            int width = getWidth();
            int height = getHeight();

            java.awt.Color color1 = new java.awt.Color(color1RR, color1GG, color1BB);
            java.awt.Color color2 = new java.awt.Color(color2RR, color2GG, color2BB);

            java.awt.GradientPaint gp = new java.awt.GradientPaint(152, 43, color1, 43, height, color2);
            g2d.setPaint(gp);
            g2d.fillRect(0, 0, width, height);
        }
    }

    public class RoundedBorder implements javax.swing.border.Border {

        private final int radius;

        public RoundedBorder(int radius) {
            this.radius = radius;
        }

        @Override
        public void paintBorder(java.awt.Component c, java.awt.Graphics g, int x, int y, int width, int height) {
            g.setColor(Color.WHITE);
            g.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }

        @Override
        public java.awt.Insets getBorderInsets(java.awt.Component c) {
            return new java.awt.Insets(this.radius + 1, this.radius + 1, this.radius + 2, this.radius);
        }

        @Override
        public boolean isBorderOpaque() {
            return true;
        }

    }

    public class JLabelTimer {

        public void invisible(JLabel label) {
            Timer timer = new Timer(3000, (ActionEvent e) -> {
                label.setVisible(false);
            });
            timer.setRepeats(false);
            timer.start();
        }
    }

    private void showToast(String s) {
        CollegeLibraryManagementSystem.JLabelTimer timer = new JLabelTimer();
        loginButton.setEnabled(false);
        toastLabel.setVisible(true);
        toastLabel.setText(s);
        timer.invisible(toastLabel);
    }

    public class CustomRenderer extends DefaultListCellRenderer {
        
        @Override
        public Component getListCellRendererComponent(JList list, Object value,
                int index, boolean isSelected, boolean cellHasFocus) {
            super.getListCellRendererComponent(list, value, index, isSelected,
                    cellHasFocus);
            setBackground(isSelected ? new java.awt.Color(120, 84, 255) : Color.BLACK);
            setForeground(new java.awt.Color(153, 255, 153));
            setHorizontalAlignment(DefaultListCellRenderer.CENTER);
            return this;
        }
    }

    class jCustomCombobox extends javax.swing.JComboBox {

        @Override
        public void setBorder(Border border) {
            super.setBorder(new RoundedBorder(5));
        }

        @Override
        public void setOpaque(boolean isOpaque) {
            super.setOpaque(false);
        }

        @Override
        public void setForeground(Color fg) {
            super.setForeground(new java.awt.Color(153, 255, 153));
        }

        @Override
        public void setBackground(Color bg) {
            super.setBackground(new java.awt.Color(35, 35, 35));
        }
    }

// Clear the present jPanel
    public void CL() {
        CardLayout.removeAll(); // Removes all the components from the jPanel
        CardLayout.repaint();
        CardLayout.revalidate();
    }

    private void studentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentButtonActionPerformed
        Student s = new Student();
        jDesktopPane1.add(s);
        s.show();
    }//GEN-LAST:event_studentButtonActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        Book b = new Book();
        jDesktopPane1.add(b);
        b.show();
    }//GEN-LAST:event_bookBtnActionPerformed

    private void bookInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookInformationBtnActionPerformed
        BookInformation bI = new BookInformation();
        jDesktopPane1.add(bI);
        bI.show();
    }//GEN-LAST:event_bookInformationBtnActionPerformed

    private void returnBooksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBooksBtnActionPerformed
        ReturnBooks rB = new ReturnBooks();
        jDesktopPane1.add(rB);
        rB.show();
    }//GEN-LAST:event_returnBooksBtnActionPerformed

    private void manageLibrarianAcBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageLibrarianAcBtnActionPerformed
        ManageLibrarianAccount mL = new ManageLibrarianAccount();
        jDesktopPane1.add(mL);
        mL.show();
    }//GEN-LAST:event_manageLibrarianAcBtnActionPerformed

    private void returnBooksBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBooksBtnMouseExited
        returnBooksBtn.setBackground(new java.awt.Color(253, 140, 4));
    }//GEN-LAST:event_returnBooksBtnMouseExited

    private void userNameTextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTextFieldKeyPressed
        loginButton.setBackground(new java.awt.Color(58, 72, 201));
        toastLabel.setVisible(false);
        if (userNameFlag) {
            userNameTextField.setText(null);
            userNameFlag = false;
        }
        passwordHintLabel1.setVisible(false);
        passwordHintLabel.setVisible(false);
    }//GEN-LAST:event_userNameTextFieldKeyPressed

    private void returnBooksBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnBooksBtnMouseEntered
        returnBooksBtn.setBackground(new java.awt.Color(51, 136, 140));
    }//GEN-LAST:event_returnBooksBtnMouseEntered

    private void studentButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentButtonMouseEntered
        studentButton.setBackground(new java.awt.Color(51, 136, 140));
        studentButton.setForeground(Color.WHITE);
    }//GEN-LAST:event_studentButtonMouseEntered

    private void bookBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseEntered
        bookBtn.setBackground(new java.awt.Color(51, 136, 140));
    }//GEN-LAST:event_bookBtnMouseEntered

    private void bookInformationBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookInformationBtnMouseEntered
        bookInformationBtn.setBackground(new java.awt.Color(51, 136, 140));
        bookInformationBtn.setForeground(Color.WHITE);
    }//GEN-LAST:event_bookInformationBtnMouseEntered

    private void manageLibrarianAcBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageLibrarianAcBtnMouseEntered
        manageLibrarianAcBtn.setBackground(new java.awt.Color(51, 136, 140));
    }//GEN-LAST:event_manageLibrarianAcBtnMouseEntered

    private void manageLibrarianAcBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageLibrarianAcBtnMouseExited
        manageLibrarianAcBtn.setBackground(new java.awt.Color(236, 88, 88));
    }//GEN-LAST:event_manageLibrarianAcBtnMouseExited

    private void bookInformationBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookInformationBtnMouseExited
        bookInformationBtn.setBackground(new java.awt.Color(77, 219, 162));
        bookInformationBtn.setForeground(new java.awt.Color(102, 102, 0));
    }//GEN-LAST:event_bookInformationBtnMouseExited

    private void bookBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bookBtnMouseExited
        bookBtn.setBackground(new java.awt.Color(57, 139, 241));
    }//GEN-LAST:event_bookBtnMouseExited

    private void studentButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentButtonMouseExited
        studentButton.setBackground(new java.awt.Color(237, 242, 133));
        studentButton.setForeground(new java.awt.Color(124, 97, 97));
    }//GEN-LAST:event_studentButtonMouseExited

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (passwordFlag) {
            passwordField.setEchoChar('\u2022');
            passwordField.setText(null);
            passwordFlag = false;
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        CL();
        CardLayout.add(Dashboard);
        BorderLayout.setPreferredSize(new java.awt.Dimension(960, 695));
    }//GEN-LAST:event_loginButtonActionPerformed

    private void loginButtonFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginButtonFocusGained
        userName = userNameTextField.getText();
        password = passwordField.getText();
        String error = null;

        try {
            String s = "SELECT * FROM LIBRARIAN ORDER BY UNAME";
            rs = st.executeQuery(s);
            rs.first();

            do {
                String userNameDb = rs.getString(1);
                String passwordDb = rs.getString(2);
                String passwordHintDb = rs.getString(3);

                if (userName.isEmpty() || userName.equals("username")) {
                    error = "Enter username.";
                    throw new Exception();
                } else if (password.isEmpty() || password.equals("password")) {
                    error = "Enter password.";
                    throw new Exception();
                }

                if (userName.equals(userNameDb)) {
                    if (password.equals(passwordDb)) {
                        loginButton.addActionListener((java.awt.event.ActionEvent evt1) -> {
                            loginButtonActionPerformed(evt1);
                        });
                        break;
                    } else {
                        error = "Incorrect Password. Please try again.";
                        passwordHintLabel1.setVisible(true);
                        passwordHintLabel.setVisible(true);
                        passwordHintLabel.setText(passwordHintDb);
                        throw new Exception();
                    }
                } else {
                    rs.next();
                    if (rs.isAfterLast()) {
                        error = "Invalid Username.";
                        throw new Exception();
                    }
                }
            } while (true);
        } catch (Exception ex) {
            showToast(error);
        }
    }//GEN-LAST:event_loginButtonFocusGained

    private void loginButtonFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_loginButtonFocusLost
        loginButton.setEnabled(true);
    }//GEN-LAST:event_loginButtonFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CollegeLibraryManagementSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(
                () -> {
                    new CollegeLibraryManagementSystem().setVisible(true);
                }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel BorderLayout;
    public javax.swing.JPanel CardLayout;
    public javax.swing.JPanel Dashboard;
    private javax.swing.JPanel LibrarianLogin;
    private javax.swing.JButton bookBtn;
    private javax.swing.JButton bookInformationBtn;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton loginButton;
    private javax.swing.JButton manageLibrarianAcBtn;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JLabel passwordHintLabel;
    private javax.swing.JLabel passwordHintLabel1;
    private javax.swing.JButton returnBooksBtn;
    private javax.swing.JButton studentButton;
    private javax.swing.JLabel toastLabel;
    public javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
