CREATE TABLE LIBRARIAN (
  UNAME VARCHAR2(30) NOT NULL UNIQUE,
  PASSWD VARCHAR2(30) NOT NULL,
  PASSWD_HINT VARCHAR2(30) NOT NULL
);

INSERT ALL
  INTO LIBRARIAN (UNAME, PASSWD, PASSWD_HINT) 
    VALUES ('bitmls1', 'yeariz2021', 'Present year')
  INTO LIBRARIAN (UNAME, PASSWD, PASSWD_HINT)
    VALUES ('bitmls2', 'willbeIitt', 'Fire')
  INTO LIBRARIAN (UNAME, PASSWD, PASSWD_HINT)
    VALUES ('bitmls3', 'earthIsGood', 'Earth')
SELECT 1 FROM DUAL;

CREATE TABLE STUDENT (  
  USN VARCHAR2(10) NOT NULL,
  STUDENT_NAME VARCHAR2(40) NOT NULL,
  BRANCH VARCHAR2(5) NOT NULL,
  SEM NUMBER(1) NOT NULL,
  ELIGIBLE VARCHAR2(3) NOT NULL,
  CONSTRAINT PK_USN PRIMARY KEY (USN)
);
  
CREATE TABLE BOOK_INFORMATION (
  SEM NUMBER(1) NOT NULL,
  BRANCH VARCHAR2(5) NOT NULL,
  BOOK_NAME VARCHAR2(50) NOT NULL,
  AUTHOR VARCHAR2(35) NOT NULL,
  BOOK_EDITION NUMBER(2),
  PUBLISHER VARCHAR2(75) NOT NULL,
  PUBLISH_YEAR NUMBER(4),
  PRICE NUMBER(4),
  NUM_OF_COPIES NUMBER(3) NOT NULL,
  RACK_NO NUMBER(2) NOT NULL,
  CONSTRAINT PK_BOOK_NAME PRIMARY KEY (BOOK_NAME)
);

CREATE TABLE BOOK (
  BOOK_ID NUMBER(15) NOT NULL,
  SEM NUMBER(1) NOT NULL,
  BRANCH VARCHAR2(5) NOT NULL,
  BOOK VARCHAR2(50) NOT NULL,
  BOOK_EDITION NUMBER(2),
  AUTHOR VARCHAR2(35) NOT NULL,
  ISBN_NO NUMBER(13) UNIQUE CHECK (LENGTH(ISBN_NO) = 13),
  CONSTRAINT PK_BOOK_ID PRIMARY KEY (BOOK_ID),
  CONSTRAINT FK_BOOK
    FOREIGN KEY (BOOK)
    REFERENCES BOOK_INFORMATION (BOOK_NAME)
);

CREATE TABLE ISSUE_BOOKS (
  USN VARCHAR2(10) NOT NULL UNIQUE,
  BOOK_ID_1 NUMBER(15),
  ISSUE_DATE_1 DATE,
  BOOK_ID_2 NUMBER(15),
  ISSUE_DATE_2 DATE,
  BOOK_ID_3 NUMBER(15),
  ISSUE_DATE_3 DATE,
  BOOK_ID_4 NUMBER(15),
  ISSUE_DATE_4 DATE,
  BOOK_ID_5 NUMBER(15),
  ISSUE_DATE_5 DATE,
  BOOK_ID_6 NUMBER(15),
  ISSUE_DATE_6 DATE,
  CONSTRAINT FK_IB_USN
    FOREIGN KEY (USN)
    REFERENCES STUDENT (USN)
    ON DELETE CASCADE,
  CONSTRAINT FK_IB_BOOK_ID_1
    FOREIGN KEY (BOOK_ID_1)
    REFERENCES BOOK(BOOK_ID),
  CONSTRAINT FK_IB_BOOK_ID_2
    FOREIGN KEY (BOOK_ID_2)
    REFERENCES BOOK(BOOK_ID),
  CONSTRAINT FK_IB_BOOK_ID_3
    FOREIGN KEY (BOOK_ID_3)
    REFERENCES BOOK(BOOK_ID),
  CONSTRAINT FK_IB_BOOK_ID_4
    FOREIGN KEY (BOOK_ID_4)
    REFERENCES BOOK(BOOK_ID),
  CONSTRAINT FK_IB_BOOK_ID_5
    FOREIGN KEY (BOOK_ID_5)
    REFERENCES BOOK(BOOK_ID),    
  CONSTRAINT FK_IB_BOOK_ID_6
    FOREIGN KEY (BOOK_ID_6)
    REFERENCES BOOK(BOOK_ID)        
);

COMMIT;